language: node_js
compiler: default
node_js: 
  - '8'
  - '9'

before_install:
  - sudo apt-get install libstdc++6
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q

install:
  - npm install

script:
  - npm test
