language: node_js
compiler: default
node_js: 
  - '8'

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -yq update
  - sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-6

install:
  - npm install

script:
  - npm test