language: node_js
compiler: default
node_js: 
  - '8'
  - '9'

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade

install:
  - npm install

script:
  - npm test
