language: node_js
compiler: default
node_js: 
  - '8'

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade

install:
  - npm install

script:
  - npm test
